title: Andrew H. Yi

repository: AndrewHYi/andrewhyi.github.io

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/AndrewHYi"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "Contact"
    link: "/contact"

favicon: yes
favicon_location: "/favicon.ico"