# Permalinks
permalink:           pretty

# Setup
title:               Andrew H. Yi
tagline:             Learn, Do, Repeat
url:                 https://www.andrewyi.xyz
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Andrew H. Yi
  url:               https://www.andrewyi.xyz
  email:             andrew.yi50@gmail.com

# Custom vars
version:             1.0.0
github:              https://github.com/AndrewHYi

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

theme: jekyll-theme-cayman