title: Andrew H. Yi

repository: AndrewHYi/andrewhyi.github.io

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/andrewhyi"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "Contact"
    link: "/contact"
